export const WALLET_LOADED = 'WALLET_LOADED';
export const CONTRACT_LOADED = 'CONTRACT_LOADED';
export const IMAGE_LOADED = 'IMAGE_LOADED';
export const LISTINGS_LOADED = 'LISTINGS_LOADED';
export const CLOSED_LISTINGS_LOADED = 'CLOSED_LISTINGS_LOADED';
export const LISTING_ID_LOADED = 'LISTING_ID_LOADED';
export const BID_AMOUNT_CHANGED = 'BID_AMOUNT_CHANGED';